### ISSUE TITLE
Backport javax.net.ssl.SNIHostName

### ISSUE THREAD

**Issue by rynkowsg** [SgtSilvio/android-retrofix#6]
Thanks for making this project. It looks very useful and actually it led me to idea how to solve my own issue.

I'm struggling with the latest Paho versions due to `javax.net.ssl.SNIHostName` (more: https://github.com/eclipse/paho.mqtt.java/issues/633).

Do you expect to backport javax.net.ssl.SNIHostName anytime soon?

Thanks again.

**Comment by SgtSilvio** [comment]
Hi @rynkowsg 
I am pretty sure that backporting SNIHostName will not work. The problem is that the SNIHostName is passed to the Java TLS implementation which has to know what to do with the SNIHostName.
Backporting completely new APIs (such as java.util.streams, CompletableFuture or java.time) works as they are isolated from other code.
If you need an MQTT client library that has support for SNI and works on Android < 7, you could use the HiveMQ MQTT Client: https://github.com/hivemq/hivemq-mqtt-client
